apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: py-syncer
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi 
  storageClassName: gp3 