apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS-ACCOUNT-ID>:role/image-syncer
  name: py-syncer
  namespace: test
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: test
  name: py-syncer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: py-syncer
  namespace: test
subjects:
- kind: ServiceAccount
  name: py-syncer
  namespace: test
roleRef:
  kind: ClusterRole
  name: py-syncer
  apiGroup: rbac.authorization.k8s.io  